#define XML_CONTEXT_BYTES 1024

#define XML_GE 0
#define XML_NS 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMMOVE 1
#define HAVE_GETRANDOM 0
#define XML_DEV_URANDOM 1
#define HAVE_ARC4RANDOM_BUF 1
#define PACKAGE_VERSION "2.7.3"
#define XML_ATTR_INFO 1
